### ISSUE TITLE
Issue whith grdreformat

### ISSUE THREAD

**Issue by Nerisson** [emolch/gmtpy#3]
When I try to use gmtpy with grdreformat, a -K option is add and according to the official documentation of GMT 5.1 this option does not exist. Is it a bad use from me of your module?

Here's my code:
<code>gmt = GMT()</code>
<code>gmt.surface(T=0.25, G="toto.nc", I="0.25m", C=0.1, R="55/56/-21.5/-20.75", in_columns=(xx, yy, zz), out_discard=True)</code>
<code>gmt.grdreformat("toto.nc", "toto.tiff", V="d")</code>

best regards,

Simon

**Comment by emolch** [comment]
Hi Simon,

please try adding the keyword argument `out_discard=True` and maybe also `supress_defaults=True` to the call to grdreformat. This will prevent gmtpy from automatically adding -K, -O and +gmtdefaults.

best regards
Sebastian

**Comment by Nerisson** [comment]
OK, thanks for the quick support, it works with <code>supress_defaults=True</code> 

Simon
