### ISSUE TITLE
failing for GMT5.1.1

### ISSUE THREAD

**Issue by iceseismic** [emolch/gmtpy#4]
Hi,
I can get to gmt=GMT()  happily when using GMT version 4.5.5 , but it fails for  GMT version 5.1.1 with the following : 

Traceback (most recent call last):
  File "test1.py", line 29, in <module>
    gmt = GMT()
  File "/sp/prj/tvz95/mypython2/lib/python2.7/site-packages/gmtpy.py", line 2850, in **init**
    self.installation = get_gmt_installation(version)
  File "/sp/prj/tvz95/mypython2/lib/python2.7/site-packages/gmtpy.py", line 1161, in get_gmt_installation
    setup_gmt_installations()
  File "/sp/prj/tvz95/mypython2/lib/python2.7/site-packages/gmtpy.py", line 1045, in setup_gmt_installations
    gmtversion, gmthome, gmtbin = check_detect_gmt_installation()
  File "/sp/prj/tvz95/mypython2/lib/python2.7/site-packages/gmtpy.py", line 976, in check_detect_gmt_installation
    return detect_gmt_installation()
  File "/sp/prj/tvz95/mypython2/lib/python2.7/site-packages/gmtpy.py", line 963, in detect_gmt_installation
    gmtversion = get_gmt_version(pjoin(gmtbin, 'gmtdefaults'), gmthome)
  File "/sp/prj/tvz95/mypython2/lib/python2.7/site-packages/gmtpy.py", line 946, in get_gmt_version
    gmtdefaultsbinary)
Exception: Can't extract version number from output of /opt/local/gmt/GMT5.1.1/bin/gmtdefaults

any suggestions ?  

Perhaps the top of  "gmtdefaults" under GMT 5.1.1  is different to previous earlier GMT v4  ??  

A command-line ">gmtdefaults"    (using v5.1.1) results in : 
# 
# GMT 5.1.1 Defaults file
# vim:sw=8:ts=8:sts=8
# $Revision: 12822 $
# $LastChangedDate: 2014-02-01 00:39:56 +0100 (Sat, 01 Feb 2014) $
#

**Comment by emolch** [comment]
Sorry, gmtpy does not yet work with GMT 5. I have been working on this already a while ago but did not have enough time to finish. The work I have done so far is in this commit in the Pyrocko package (where I included a copy of the gmtpy module) https://github.com/emolch/pyrocko/commit/ab68f2ac51963e0dd01bbe353af6600de455f054 Basic things already work, but there are still some problems with layouts and backward compatibility with GMT 4.

**Comment by iceseismic** [comment]
Thanks very much for the reply Sebastian ;
Cheers
Stephen

Sent from IBM Notes Traveler


   Sebastian Heimann --- Re: [gmtpy] failing for GMT5.1.1 (#4) --- 
    From:"Sebastian Heimann" <notifications@github.com>To"emolch/gmtpy" <gmtpy@noreply.github.com>Cc"iceseismic" <s.bannister@gns.cri.nz>Date:Fri, 31 Jul 2015 19:55SubjectRe: [gmtpy] failing for GMT5.1.1 (#4)
  
  Sorry, gmtpy does not yet work with GMT 5. I have been working on this already a while ago but did not have enough time to finish. The work I have done so far is in this commit in the Pyrocko package (where I included a copy of the gmtpy module) emolch/pyrocko@ab68f2a Basic things already work, but there are still some problems with layouts and backward compatibility with GMT 4. 
  —Reply to this email directly or view it on GitHub.

Notice: This email and any attachments are confidential.
If received in error please destroy and immediately notify us.
Do not copy or disclose the contents.

**Comment by emolch** [comment]
Has been a long time, but now, finally, gmtpy works with GMT5 (5.3.1 has been tested). 

Many thanks to @tmwilley who backported the GMT5 support from pyrocko.gmtpy to standalone gmtpy.
